---
title: "resume"
format:
  html: 
    theme: cosmo
    mainfont: Times New Roman
    fontsize: 1.1em
    fontcolor: rebeccapurple
    linkcolor: red
---

## Resume

<html>

<head>

```{=html}
<style>
.center {
  text-align: center;
}
</style>
```
</head>

<body>

::: center
<h3>Job Application: Data Analyst</h3>
:::

### Education

| SCHOOL                                            | MAJOR                                | DEGREE      |
|-------------------------------|-----------------------|------------------|
| **Hebei University of Environmental Engineering** | Internet of things                   | Engineering |
| **University of Illinois Chicago**                | Master of Science in Civic Analytics | Master      |

### Skills

1.Statistical knowledge: Data analysts need to have a solid foundation in statistics and be able to understand and apply various statistical tests and models to analyze data sets.

2.Programming skills: Master programming languages related to data analysis, such as Python or R.

3.Data Processing and Cleaning: Ability to use software tools or programming skills to process and clean data, including handling missing data, outliers, and erroneous data for analysis.

4.Data Visualization: Ability to use RStudio for data visualization.

5.Database Management: Understand database management systems, such as SQL, and be able to efficiently retrieve data from databases.

6.Machine Learning: Understand basic machine learning concepts and techniques, including supervised and unsupervised learning, and how to use them to analyze complex data sets.

7.Problem-solving skills: Able to flexibly think and solve problems when faced with problems that arise during data analysis.

8.Project Management: Ability to manage data analytics projects, including planning project timelines, allocating resources, and coordinating team members.

### Experience

1.Participated in merchandise sales activities during college and has good communication skills.

2.I once worked for Tesla, responsible for vehicle and system development and testing, and participated in many Tesla project discussions.
